# -*- coding: utf-8 -*-
"""run.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ccfbN6DFMmaszqUN9ZYVOJLQSiSB1Ntx
"""

#Project: Parking Slot Occupancy Detection
#Model: YOLOv8 (custom) – parking82_best.pt
#Video: hack17.mp4 (~2532 frames, 848x480, ~30 FPS)

#How to run:
#1) Install dependencies:
 #  pip install ultralytics opencv-python pandas numpy
#2) Place files in the same folder:
#  - hack18.mp4
  # - slots_frame1.json, slots_frame2.json, ...
   #- parking82_best.pt
   -# run.py
#3) Run the script:
 #  python run.py

#Outputs:
#- output_parking_legend_style.mp4
#- slot_status_log.csv / slot_status_log.xlsx

#Notes:
#- Frame-based JSON mapping:
#  1–655 -> slots_frame1.json
# 656–1570 -> slots_frame4.json
# 1571–2380-> slots_frame12.json
# 2381–end -> slots_frame12.json
#- Smoothing: majority vote over last 5 frames per slot

!pip install ultralytics

import cv2
import torch
import json
import csv
import pandas as pd
from ultralytics import YOLO
from collections import defaultdict, deque
import numpy as np
from datetime import datetime

# ---------------------------
# Parameters
# ---------------------------
INPUT_VIDEO = "hack18.mp4"
OUTPUT_VIDEO = "output_parking_legend_style.mp4"
OUTPUT_CSV = "slot_status_log.csv"
OUTPUT_XLSX = "slot_status_log.xlsx"
MODEL_PATH = "parking82_best.pt"
SMOOTHING_WINDOW = 5  # frames for majority voting

# JSON files for different frame ranges
SLOTS_FRAME1_JSON = "slots_frame1.json"
SLOTS_FRAME2_JSON = "slots_frame4.json"
SLOTS_FRAME3_JSON = "slots_frame12.json"
SLOTS_FRAME4_JSON = "slots_frame5.json"
# Frame ranges
FRAME_RANGES = [
    (1, 655, SLOTS_FRAME1_JSON),
    (656, 1570, SLOTS_FRAME2_JSON),
    (1571, 2380, SLOTS_FRAME3_JSON),
    (2381, None, SLOTS_FRAME4_JSON)
]

# ---------------------------
# Load YOLOv8 model
# ---------------------------
model = YOLO(MODEL_PATH)

# ---------------------------
# Load slot markers for all JSONs
# ---------------------------
slots_frame1 = json.load(open(SLOTS_FRAME1_JSON))
slots_frame2 = json.load(open(SLOTS_FRAME2_JSON))
slots_frame3 = json.load(open(SLOTS_FRAME3_JSON))
slots_frame4 = json.load(open(SLOTS_FRAME4_JSON))
# ---------------------------
# Video setup
# ---------------------------
cap = cv2.VideoCapture(INPUT_VIDEO)
w = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
h = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps = cap.get(cv2.CAP_PROP_FPS)
total_frames = int(cap.get(cv2.CAP_PROP_FRAME_COUNT))

fourcc = cv2.VideoWriter_fourcc(*'mp4v')
out = cv2.VideoWriter(OUTPUT_VIDEO, fourcc, fps, (w, h))

# ---------------------------
# Smoothing buffers
# ---------------------------
slot_history = defaultdict(lambda: deque(maxlen=SMOOTHING_WINDOW))

# ---------------------------
# Legend config
# ---------------------------
legend_items = {
    "Empty": (0, 255, 0),
    "Occupied": (0, 0, 255),
    "Transition": (0, 255, 255)
}

def draw_legend(frame, slot_status_counts):
    overlay = frame.copy()
    start_x, start_y = 10, 10
    width, height = 180, 100
    alpha = 0.6
    cv2.rectangle(overlay, (start_x, start_y), (start_x + width, start_y + height), (50, 50, 50), -1)
    cv2.addWeighted(overlay, alpha, frame, 1 - alpha, 0, frame)
    for idx, (label, color) in enumerate(legend_items.items()):
        y = start_y + 25 + idx * 25
        cv2.rectangle(frame, (start_x + 10, y - 12), (start_x + 30, y + 8), color, -1)
        count = slot_status_counts.get(label, 0)
        text = f"{label}: {count}"
        cv2.putText(frame, text, (start_x + 40, y), cv2.FONT_HERSHEY_TRIPLEX, 0.5, color, 1, cv2.LINE_AA)

# ---------------------------
# Helper function to assign detection to nearest slot
# ---------------------------
def assign_slot(cx, cy, slot_markers):
    min_dist = float('inf')
    assigned_slot = None
    for slot_id, coord in slot_markers.items():
        sx, sy = coord
        dist = ((cx - sx) ** 2 + (cy - sy) ** 2) ** 0.5
        if dist < min_dist:
            min_dist = dist
            assigned_slot = slot_id
    return assigned_slot

# ---------------------------
# CSV Logging Setup
# ---------------------------
csv_file = open(OUTPUT_CSV, mode="w", newline="")
csv_writer = csv.writer(csv_file)
csv_writer.writerow(["timestamp", "frame_idx", "slot_id", "status", "confidence"])

# ---------------------------
# Process video
# ---------------------------
frame_idx = 0
while True:
    ret, frame = cap.read()
    if not ret:
        break
    frame_idx += 1
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

    # ---------------------------
    # Select slot markers based on frame_idx
    # ---------------------------
    if frame_idx <= 655:
        slot_markers = slots_frame1
    elif frame_idx <= 1570:
        slot_markers = slots_frame2
    elif frame_idx <= 2380:
        slot_markers = slots_frame3
    else:
        slot_markers = slots_frame4

    # ---------------------------
    # YOLO inference
    # ---------------------------
    results = model(frame, verbose=False)
    slot_detections = {slot_id: [] for slot_id in slot_markers.keys()}

    for r in results:
        for box in r.boxes:
            cls_id = int(box.cls[0])
            conf = float(box.conf[0])
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            cx, cy = (x1 + x2) // 2, (y1 + y2) // 2

            slot_id = assign_slot(cx, cy, slot_markers)
            if slot_id is not None:
                slot_detections[slot_id].append((cls_id, conf))

    # ---------------------------
    # Update slot history & draw
    # ---------------------------
    slot_status_counts = {"Empty": 0, "Occupied": 0, "Transition": 0}

    for slot_id, dets in slot_detections.items():
        if dets:
            cls_id = max(set([d[0] for d in dets]), key=[d[0] for d in dets].count)
            conf = np.mean([d[1] for d in dets])
        else:
            cls_id = 0
            conf = 1.0

        slot_history[slot_id].append(cls_id)
        final_cls = max(set(slot_history[slot_id]), key=slot_history[slot_id].count)

        # Map to label & color
        if final_cls == 0:
            label, color = "Empty", (0, 255, 0)
        elif final_cls == 1:
            label, color = "Occupied", (0, 0, 255)
        elif final_cls == 2:
            label, color = "Transition", (0, 255, 255)
        else:
            label, color = "Unknown", (255, 255, 255)

        slot_status_counts[label] = slot_status_counts.get(label, 0) + 1

        # Log CSV
        csv_writer.writerow([timestamp, frame_idx, slot_id, label, round(conf, 2)])

        # Draw square marker & label
        sx, sy = slot_markers[slot_id]
        size = 8
        cv2.rectangle(frame, (sx - size, sy - size), (sx + size, sy + size), color, -1)
        slot_number = slot_id.replace("slot", "")
        text_pos = (sx - size, sy - size - 5)
        cv2.putText(frame, f"Slot {slot_number}", text_pos, cv2.FONT_HERSHEY_TRIPLEX, 0.5, color, 1, cv2.LINE_AA)

    # Draw legend
    draw_legend(frame, slot_status_counts)

    out.write(frame)

    # Optional progress print
    if frame_idx % 100 == 0:
        print(f"Processing frame {frame_idx}/{total_frames}")

# ---------------------------
# Cleanup
# ---------------------------
csv_file.close()
cap.release()
out.release()

# Convert CSV → Excel
df = pd.read_csv(OUTPUT_CSV)
df.to_excel(OUTPUT_XLSX, index=False)

print(f"✅ Processed video saved as {OUTPUT_VIDEO}")
print(f"✅ Slot logs saved as {OUTPUT_CSV} and {OUTPUT_XLSX}")

from google.colab import files
files.download("output_parking_legend_style.mp4")

from google.colab import files
files.download("slot_status_log.csv")

from google.colab import files
files.download("slot_status_log.xlsx")