# -*- coding: utf-8 -*-
"""Untitled8.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14zCdCqVb8blQ92hD94QYBe6FqASJyuSE
"""

from google.colab import drive
drive.mount('/content/drive')

!rm -rf /content/dataset
!mkdir /content/dataset

!unzip -o "/content/drive/MyDrive/H&H/parking/parking_slots.v2i.yolov8.zip" -d /content/dataset
!unzip -o "/content/drive/MyDrive/H&H/parking/parking_slots.v3i.yolov8.zip" -d /content/dataset
!unzip -o "/content/drive/MyDrive/H&H/parking/parking_slots.v4i.yolov8.zip" -d /content/dataset
!unzip -o "/content/drive/MyDrive/H&H/parking/parking_slots.v5i.yolov8.zip" -d /content/dataset
!unzip -o "/content/drive/MyDrive/H&H/parking/parking_slots.v6i.yolov8.zip" -d /content/dataset

!ls /content/dataset

!pip install ultralytics

from ultralytics import YOLO

# Load YOLOv8 model (choose 'yolov8n.pt', 'yolov8s.pt', etc.)
model = YOLO("yolov8n.pt")

# Train
model.train(
    data="/content/dataset/data.yaml",  # path to data.yaml
    epochs=50,                          # increase if dataset is big
    imgsz=640,                          # image size
    batch=16,                           # adjust if Colab RAM is low
    name="parking82_best"
)